// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFZAuP_Krj8KjYUHXBNcGxOryc_QGQbDI',
    appId: '1:272433796228:web:35d9d0cf9f509d2356ded1',
    messagingSenderId: '272433796228',
    projectId: 'oxys-v1',
    authDomain: 'oxys-v1.firebaseapp.com',
    storageBucket: 'oxys-v1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQyFKunDsMI3uL46AWSAmBu87PUoLIqI',
    appId: '1:272433796228:android:4e06026bf92ff42f56ded1',
    messagingSenderId: '272433796228',
    projectId: 'oxys-v1',
    storageBucket: 'oxys-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ42GT06buhdyzS_QaNG5HzsiJ4hZ0hXs',
    appId: '1:272433796228:ios:5ba021310ac6d58a56ded1',
    messagingSenderId: '272433796228',
    projectId: 'oxys-v1',
    storageBucket: 'oxys-v1.appspot.com',
    iosClientId: '272433796228-791mmc29pat3a8id8s0mkrtouc7mk921.apps.googleusercontent.com',
    iosBundleId: 'com.example.oxys',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ42GT06buhdyzS_QaNG5HzsiJ4hZ0hXs',
    appId: '1:272433796228:ios:5ba021310ac6d58a56ded1',
    messagingSenderId: '272433796228',
    projectId: 'oxys-v1',
    storageBucket: 'oxys-v1.appspot.com',
    iosClientId: '272433796228-791mmc29pat3a8id8s0mkrtouc7mk921.apps.googleusercontent.com',
    iosBundleId: 'com.example.oxys',
  );
}
